apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/name: postgres-operator
  name: postgres-operator-webhook
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/name: postgres-operator
status:
  loadBalancer: {}
