#!/usr/bin/env python3
"""Sync the Helm chart's CRD templates from ``config/crd/`` — the source of truth.

For each ``config/crd/<name>.yaml`` we emit
``charts/postgres-operator/templates/<name>-crd.yaml`` wrapped in two Helm
conditionals:

* ``{{- if .Values.crd.install -}}`` ... ``{{- end }}`` around the whole file,
  so operators can opt out and install CRDs out-of-band (e.g. by a cluster
  admin while the operator chart is deployed by a developer).
* ``{{- if .Values.crd.keep }}`` ... ``{{- end }}`` around an injected
  ``helm.sh/resource-policy: keep`` annotation so ``helm uninstall`` does not
  delete the CRDs (and every PostgresCluster they own) by default.

We deliberately don't run YAML through a parser/serializer round-trip: that
would reorder keys and produce noisy diffs against the source CRDs. Instead
we treat the source files as text and surgically insert the Helm annotation
block right after the first ``metadata:`` line. The CRDs ship from this repo
with no existing ``metadata.annotations``, so the inject is always safe.

Run via ``make chart-sync-crds`` (regenerate) or ``make chart-check`` (verify
the chart matches what the script would generate, suitable for CI).
"""

from __future__ import annotations

import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SRC_DIR = REPO / "config" / "crd"
DST_DIR = REPO / "charts" / "postgres-operator" / "templates"

HEADER = "{{- if .Values.crd.install -}}\n"
FOOTER = "{{- end }}\n"

ANNOTATION_BLOCK = (
    "  {{- if .Values.crd.keep }}\n"
    "  annotations:\n"
    '    "helm.sh/resource-policy": keep\n'
    "  {{- end }}\n"
)

AUTOGEN_BANNER = (
    "# AUTOGENERATED from config/crd/{src_name} by hack/sync-chart-crds.py.\n"
    "# Edit the source CRD and run `make chart-sync-crds`; do not edit this file.\n"
)


def transform(src_text: str, src_name: str) -> str:
    """Wrap the source CRD with Helm conditionals and the keep annotation."""
    lines = src_text.splitlines(keepends=True)
    out: list[str] = [HEADER, AUTOGEN_BANNER.format(src_name=src_name)]
    metadata_seen = False
    for line in lines:
        out.append(line)
        if not metadata_seen and line.rstrip() == "metadata:":
            out.append(ANNOTATION_BLOCK)
            metadata_seen = True
    if not metadata_seen:
        raise SystemExit(
            f"sync-chart-crds: {src_name} has no top-level `metadata:` line; "
            "the script can't inject the keep-annotation. Check the CRD."
        )
    if not out[-1].endswith("\n"):
        out.append("\n")
    out.append(FOOTER)
    return "".join(out)


def expected_targets() -> dict[pathlib.Path, str]:
    """Map of expected chart-template path -> expected content."""
    targets: dict[pathlib.Path, str] = {}
    for src in sorted(SRC_DIR.glob("*.yaml")):
        # config/crd/postgres-cluster.yaml -> templates/postgres-cluster-crd.yaml
        dst = DST_DIR / f"{src.stem}-crd.yaml"
        targets[dst] = transform(src.read_text(), src.name)
    return targets


def cmd_sync() -> int:
    targets = expected_targets()
    # Remove any *-crd.yaml in templates/ that don't have a source — protects
    # against renames and stale files.
    keep_names = {p.name for p in targets}
    for stale in DST_DIR.glob("*-crd.yaml"):
        if stale.name not in keep_names:
            stale.unlink()
            print(f"removed stale {stale.relative_to(REPO)}")
    for dst, content in targets.items():
        dst.write_text(content)
        print(f"wrote {dst.relative_to(REPO)}")
    return 0


def cmd_check() -> int:
    targets = expected_targets()
    drifted: list[str] = []
    for dst, expected in targets.items():
        actual = dst.read_text() if dst.exists() else ""
        if actual != expected:
            drifted.append(str(dst.relative_to(REPO)))
    if drifted:
        print(
            "chart CRD templates are out of sync with config/crd/:\n  "
            + "\n  ".join(drifted)
            + "\nRun `make chart-sync-crds` to regenerate.",
            file=sys.stderr,
        )
        return 1
    print("chart CRD templates are in sync with config/crd/")
    return 0


def main(argv: list[str]) -> int:
    if len(argv) != 2 or argv[1] not in {"sync", "check"}:
        print("usage: sync-chart-crds.py {sync|check}", file=sys.stderr)
        return 2
    return cmd_sync() if argv[1] == "sync" else cmd_check()


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
